DATASET:
  NAME: vg_coco
  TYPE: gen 
MODEL:
  NAME: GraphPool 
  TARGET: SBERT
  BATCH_SIZE: 32
  LR: 0.0001
  WORD_EMB_SIZE: 300
  NUM_HIDDEN: 256
  TAIL_RANGE: 100
  SAMPLE_MODE: tail_random 
  MODE: adj 
  ALGO: DiffPool 
  NUM_MAX_HE: 100
  STEP: 3
  NUM_POOLED: 100
