DATASET:
  NAME: vg_coco
  TYPE: gen
MODEL:
  TARGET: SBERT
  BATCH_SIZE: 18
  LR: 0.0001
  NUM_MAX_HE: 100
  STEP: 3
  WORD_EMB_SIZE: 256
  NUM_HIDDEN: 256
  NUM_HEAD: 8
  TAIL_RANGE: 100
  SAMPLE_MODE: tail_random 
  MODE: bbox_word 
  FEATURE: bbox_word_cat
  FINETUNE: True 



