DATASET:
  NAME: coco
MODEL:
  TARGET: SBERT
  BATCH_SIZE: 32
  LR: 0.0001
  NUM_MAX_HE: 100
  STEP: 3
  WORD_EMB_SIZE: 300
  NUM_HIDDEN: 256
  NUM_HEAD: 8
  TAIL_RANGE: 100
  SAMPLE_MODE: tmb 
  MODE: word



