DATASET:
  NAME: "f30k"
MODEL:
  TARGET: SBERT
  BATCH_SIZE: 8
  LR: 0.0001
  NUM_MAX_HE: 200
  STEP: 3
  WORD_EMB_SIZE: 300
  NUM_HIDDEN: 256
  NUM_HEAD: 8
  TAIL_RANGE: 200
  NUM_SAMPLE_PER_RANGE: 3



