DATASET:
  NAME: vg_coco
  TYPE: grcnn 
MODEL:
  NAME: GraphEmbedding
  TARGET: SBERT
  BATCH_SIZE: 32
  LR: 0.0001
  NUM_MAX_HE: 100
  STEP: 3
  WORD_EMB_SIZE: 300
  NUM_HIDDEN: 300
  TAIL_RANGE: 100
  SAMPLE_MODE: tail_random 
  MODE: adj 
  ALGO: GIN
  MLP_HIDDEN: 64



