DATASET:
  NAME: vg_coco
  TYPE: gen 
MODEL:
  NAME: HGAN_V3
  TARGET: SBERT
  VER: 2
  BATCH_SIZE: 32
  LR: 0.0001
  NUM_MAX_HE: 100
  STEP: 3
  NUM_HEAD: 300
  WORD_EMB_SIZE: 300
  NUM_HIDDEN: 300
  TAIL_RANGE: 100
  SAMPLE_MODE: tail_random 
  MODE: word 



