DATASET:
  NAME: vg_coco
  TYPE: gen
MODEL:
  TARGET: SBERT
  BATCH_SIZE: 32
  LR: 0.0001
  NUM_MAX_HE: 100
  STEP: 3
  WORD_EMB_SIZE: 512
  NUM_HIDDEN: 256
  NUM_HEAD: 8
  TAIL_RANGE: 100
  SAMPLE_MODE: tail_random 
  MODE: fixedbbox 
  FEATURE: bbox
  FINETUNE: True
  bbox_size: 112



